//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loginweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billinfo
    {
        public int id { get; set; }
        public int idbill { get; set; }
        public int idfood { get; set; }
        public int count { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual food food { get; set; }
    }
}
