//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loginweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.billinfoes = new HashSet<billinfo>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> datecheckin { get; set; }
        public Nullable<System.DateTime> datecheckout { get; set; }
        public string status { get; set; }
        public int idaccount { get; set; }
        public int idtable { get; set; }
    
        public virtual account account { get; set; }
        public virtual tablefood tablefood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billinfo> billinfoes { get; set; }
    }
}
